### ISSUE TITLE
private_key_filename?

### ISSUE THREAD

**Issue by doverradio** [CoderJoshDK/WIOpy#2]
Hello, 

I am trying to use WIOpy but I do not know where to create the private_key_filename.  

Please can you share how to do this?

Thank you!

**Comment by CoderJoshDK** [comment]
If you follow https://walmart.io/key-tutorial it generates both public and private keys. Find the location of the file. For `private_key_filename`, provide the class with either the relative location of the file or the absolute location of the file. You can always copy the private key file into any project folder you are using.
For best security, do not put the private key into that folder and just reference the same location every time. If you did have the file in the same location of the code, an example of a call would be: `private_key_filename='./WM_IO_private_key.pem'`
Otherwise an absolute path like: `private_key_filename='/Users/{user}/{folder}/WM_IO_private_key.pem'`
I hope this helps

**Comment by doverradio** [comment]
Worked! Thank you so much!
